
title = "Clyde Dialogue"
description = "Clyde is a language for writing game dialogues. It supports branching, translations and interfacing with your game through variables and events."
keywords="clyde,dialogue,game dialogue,godot,plugin"
image = "icon.png"
url="https://thisisvini.com/clyde"
